In [54]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDClassifier
from sklearn.utils import shuffle
from sklearn.preprocessing import PolynomialFeatures
import plotly.graph_objs as go
import plotly.offline as ply
import time
import cufflinks as cf

cf.go_offline()
cf.set_config_file(offline=False, world_readable=True)

rand = np.random.rand(100)

g_1 = 50 * rand[50:] + 300
g_2 = 50 * rand[:50] + 32

y = np.ones((100,))
y[:50] = 0

X = np.hstack((g_1, g_2))
X = np.vstack((range(100), X)).T

X, y = shuffle(X, y)

poly = PolynomialFeatures(1)
X = poly.fit_transform(X)

# for i in range(1, 500):
#     plt.scatter(X[:, 1], X[:, 2])
#
#     clf = SGDClassifier(loss='log', max_iter=i, tol=1e-3)
#
#     clf.fit(X, y)
#
#     theta = (clf.coef_).flatten()
#
#     plt.plot(range(100), -(theta[0] + theta[1] * range(100)) / theta[2])
#
#     plt.show()
#     time.sleep(0.2)

clf = SGDClassifier(loss='log', max_iter=1000, tol=1e-3)

clf.fit(X, y)

theta = (clf.coef_).flatten()
ind=np.argsort(X[:,1])
X=X[ind]
# X = np.sort(X, axis=0)
data = np.zeros((int(X[:, 1].max() - X[:,1].min()), int(X[:, 2].max() - X[:, 2].min())))
for i, k in zip(range(int(X[:,1].min()), int(X[:, 1].max())), range(int(X[:, 1].max() - X[:,1].min()))):
    for j, l in zip(range(int(X[:,2].min()), int(X[:, 2].max())), range(int(X[:, 2].max() - X[:, 2].min()))):
#         print(i, j)
        data[k][l] = clf.predict(np.array([1, i, X[k, 2]]).reshape(1, -1))

fig = go.Figure(data = [go.Surface(z=data)])
fig.show()
print(X)


[[  1.           0.         319.86662797]
 [  1.           1.         306.55960981]
 [  1.           2.         313.86365356]
 [  1.           3.         345.95348744]
 [  1.           4.         305.17940919]
 [  1.           5.         346.73113844]
 [  1.           6.         304.41044187]
 [  1.           7.         320.76737577]
 [  1.           8.         303.72789967]
 [  1.           9.         338.13344334]
 [  1.          10.         337.9614396 ]
 [  1.          11.         314.90060281]
 [  1.          12.         333.72910823]
 [  1.          13.         306.97818822]
 [  1.          14.         335.75399514]
 [  1.          15.         339.37293311]
 [  1.          16.         342.63620902]
 [  1.          17.         331.50320022]
 [  1.          18.         302.5989795 ]
 [  1.          19.         323.68219188]
 [  1.          20.         341.82093298]
 [  1.          21.         324.97150197]
 [  1.          22.         343.89139484]
 [  1.          23.         315.77

In [37]:
print(X)

[[  1.           0.          32.18600486]
 [  1.           1.          34.91689372]
 [  1.           2.          35.01692991]
 [  1.           3.          36.66664653]
 [  1.           4.          38.07515299]
 [  1.           5.          38.32634167]
 [  1.           6.          39.21985592]
 [  1.           7.          39.87670967]
 [  1.           8.          40.48047322]
 [  1.           9.          41.11172278]
 [  1.          10.          41.63806781]
 [  1.          11.          44.16917945]
 [  1.          12.          44.5614491 ]
 [  1.          13.          44.73551974]
 [  1.          14.          44.79245333]
 [  1.          15.          44.92331932]
 [  1.          16.          45.70651867]
 [  1.          17.          45.8239992 ]
 [  1.          18.          45.83130726]
 [  1.          19.          47.39666862]
 [  1.          20.          47.48276634]
 [  1.          21.          48.61160176]
 [  1.          22.          49.99995235]
 [  1.          23.          50.06